### ISSUE TITLE
森空岛签到不上了

### ISSUE THREAD

**Issue by Loile11** [tuotuooo/AutoLiver#10]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\依依\Downloads\AutoLiver-main (1)\AutoLiver-main\skd\qd_request.py", line 143, in <module>
    cred, token = get_cred(code)
                  ^^^^^^^^^^^^^^
  File "C:\Users\依依\Downloads\AutoLiver-main (1)\AutoLiver-main\skd\qd_request.py", line 136, in get_cred
    if response.json()['code'] == 0:
       ^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Loile11** [comment]
签到就会报这个错误

**Comment by tuotuooo** [comment]
作者逆向能力有限，原签到请求的核心代码来自`HaneRo`，暂时尚未更新。
目前已有其他大佬解决了此次报错问题，https://gitee.com/FancyCabbage/skyland-auto-sign
