### ISSUE TITLE
库街区登陆报错

### ISSUE THREAD

**Issue by Arthoth** [tuotuooo/AutoLiver#9]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Sign-IN\AutoLiver-main (2)\AutoLiver-main\kjq\phone_login.py", line 50, in <module>
    main()
  File "C:\Users\user\Desktop\Sign-IN\AutoLiver-main (2)\AutoLiver-main\kjq\phone_login.py", line 41, in main
    fdsf = eee(phone, code, hex_string)
  File "C:\Users\user\Desktop\Sign-IN\AutoLiver-main (2)\AutoLiver-main\kjq\phone_login.py", line 30, in eee
    token = parsed_data['data']['token']
KeyError: 'data'

**Comment by tuotuooo** [comment]
![image](https://github.com/user-attachments/assets/24740892-8f82-406b-8a97-0dfd1227540b)
验证请求头时增加了需要验证的参数，`devcode`，🦉已更新
